version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=node00
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    tty: true
  db:
    image: postgres:11
    ports:
      - "5432"
    environment:
      POSTGRES_DB: novaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novaSecret
  django:
    build: ./back
    volumes:
      - ./back:/code
    ports:
      - "7000:7000"
    command: >
      /bin/bash -c "
        while ! curl -X GET elasticsearch:9200/_cluster/health --silent;
        do
          sleep 1;
        done;
        python manage.py runserver 0.0.0.0:7000 "
    depends_on:
      - db
      - elasticsearch
  react:
    build: ./front
    volumes:
      - ./front/uv-energy-front:/code
    ports:
      - "8000:3000"
    depends_on:
      - django

